'use client';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { ChevronDown, Loader2, Sun, Moon } from 'lucide-react';
import { useEffect, useId, useRef, useState } from 'react';
import { cn } from '@/lib/utils'; import type { ApplicationStatus, CitationSource } from '@/lib/types';

type ButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'ghost' | 'danger' };
export function Button({ className, variant = 'primary', children, ...props }: ButtonProps) {
    const variants = { primary: 'bg-accent text-white border-accent hover:brightness-110', secondary: 'bg-surface-2 text-text-primary border-border-strong hover:bg-surface-3', ghost: 'bg-transparent text-text-secondary border-border hover:text-text-primary hover:bg-surface-2', danger: 'bg-transparent text-negative border-negative hover:bg-surface-2' };
    return <button className={cn('inline-flex min-h-9 items-center justify-center gap-2 rounded-card border px-3.5 py-2 text-13 font-medium disabled:pointer-events-none disabled:opacity-40', variants[variant], className)} {...props}>{children}</button>
}
export function Input({ className, ...props }: React.InputHTMLAttributes<HTMLInputElement>) { return <input className={cn('h-10 w-full rounded-card border border-border bg-surface-2 px-3 text-14 text-text-primary placeholder:text-text-secondary focus:border-border-strong focus:outline-none focus:ring-2 focus:ring-accent', className)} {...props} /> }
export function Textarea({ className, ...props }: React.TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea className={cn('w-full resize-y rounded-card border border-border bg-surface-2 px-3 py-2.5 text-14 leading-6 text-text-primary placeholder:text-text-secondary focus:border-border-strong focus:outline-none focus:ring-2 focus:ring-accent', className)} {...props} /> }
export function Select({ className, children, ...props }: React.SelectHTMLAttributes<HTMLSelectElement>) { return <div className="relative"><select className={cn('h-10 w-full appearance-none rounded-card border border-border bg-surface-2 px-3 pr-9 text-14 text-text-primary focus:border-border-strong focus:outline-none focus:ring-2 focus:ring-accent', className)} {...props}>{children}</select><ChevronDown size={14} strokeWidth={1.5} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-text-secondary" /></div> }
export function Panel({ className, children }: React.HTMLAttributes<HTMLDivElement>) { return <section className={cn('panel', className)}>{children}</section> }
export function Skeleton({ className }: { className?: string }) { return <div aria-hidden className={cn('animate-pulse rounded-card border border-border bg-surface-1', className)} /> }
export function PageHeader({ eyebrow, title, description, actions }: { eyebrow: string; title: string; description?: string; actions?: React.ReactNode }) { return <header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="font-mono text-13 text-text-secondary">{eyebrow}</div><h1 className="mt-1 text-26 font-semibold tracking-[-.02em] md:text-34">{title}</h1>{description && <p className="mt-2 max-w-2xl text-14 text-text-secondary">{description}</p>}</div>{actions && <div className="shrink-0">{actions}</div>}</header> }
export function SkillChip({ label, verified = false }: { label: string; verified?: boolean }) { return <span className="inline-flex h-7 items-center gap-2 rounded-card border border-border bg-surface-2 px-2.5 font-mono text-13 text-text-secondary">{verified && <span className="size-1.5 rounded-full bg-positive" aria-label="verified" />}{label}</span> }
export function StatusPill({ status }: { status: ApplicationStatus }) { const tone = status === 'Rejected' ? 'negative' : status === 'Offer' ? 'positive' : ['Interview', 'Technical Interview', 'Screening'].includes(status) ? 'caution' : 'neutral'; return <span data-status={tone} className="inline-flex h-6 items-center rounded-card border border-border border-l-2 border-l-[var(--status-color)] bg-surface-2 px-2 font-mono text-[12px] text-text-secondary">{status}</span> }
export function CitationReference({ number, source }: { number: number; source: CitationSource }) { const [open, setOpen] = useState(false); const reduce = useReducedMotion(); const id = useId(); const ref = useRef<HTMLSpanElement>(null); useEffect(() => { if (!open) return; const fn = (e: MouseEvent) => { if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false) }; document.addEventListener('mousedown', fn); return () => document.removeEventListener('mousedown', fn) }, [open]); return <span ref={ref} onMouseEnter={() => setOpen(true)} onMouseLeave={() => setOpen(false)} className="relative ml-0.5 inline-flex align-super"><button aria-expanded={open} aria-controls={id} onClick={() => setOpen(v => !v)} onFocus={() => setOpen(true)} className="rounded-card px-0.5 font-mono text-[12px] leading-none text-text-secondary underline decoration-border-strong underline-offset-2 hover:text-text-primary">{number}</button><AnimatePresence>{open && <motion.span id={id} role="tooltip" initial={reduce ? false : { opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 4 }} transition={{ duration: .1 }} className="elevated absolute bottom-[calc(100%+10px)] left-1/2 z-40 w-[280px] -translate-x-1/2 p-3 text-left normal-case tracking-normal"><span className="flex items-center gap-2 font-mono text-[12px] text-text-secondary"><span className={cn('size-1.5 rounded-full', source.verified ? 'bg-positive' : 'bg-negative')} />{source.source}</span><span className="mt-2 block text-13 leading-5 text-text-primary">{source.detail}</span><span className="mt-2 block font-mono text-[12px] text-text-secondary">{source.id}</span></motion.span>}</AnimatePresence></span> }
export function MatchScoreRadial({ value, size = 68, animate = false, label }: { value: number; size?: number; animate?: boolean; label?: string }) { const reduce = useReducedMotion(); const tone = value >= 80 ? 'text-positive' : value >= 60 ? 'text-caution' : 'text-negative'; const r = 44; return <div className="inline-flex flex-col items-center gap-1.5"><div className={cn('relative grid place-items-center', tone)} style={{ width: size, height: size }} role="img" aria-label={`${label ?? 'Match score'} ${value}%`}><svg viewBox="0 0 100 100" className="absolute inset-0 size-full -rotate-90" aria-hidden><circle cx="50" cy="50" r={r} fill="none" stroke="var(--border-strong)" strokeWidth="2" /><motion.circle cx="50" cy="50" r={r} fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" pathLength={1} initial={animate && !reduce ? { pathLength: 0 } : false} animate={{ pathLength: value / 100 }} transition={animate && !reduce ? { type: 'spring', stiffness: 400, damping: 30 } : { duration: 0 }} /></svg><span className="font-mono text-13 text-text-primary">{value}%</span></div>{label && <span className="font-mono text-[12px] text-text-secondary">{label}</span>}</div> }
export function ThemeToggle() { const [light, setLight] = useState(false); useEffect(() => { const saved = localStorage.getItem('careerpilot-theme'); const useLight = saved === 'light'; setLight(useLight); document.documentElement.dataset.theme = useLight ? 'light' : 'dark' }, []); function toggle() { setLight(v => { const n = !v; document.documentElement.dataset.theme = n ? 'light' : 'dark'; localStorage.setItem('careerpilot-theme', n ? 'light' : 'dark'); return n }) } return <button onClick={toggle} className="grid size-9 place-items-center rounded-card border border-border bg-surface-1 text-text-secondary hover:text-text-primary" aria-label={light ? 'Use dark mode' : 'Use light mode'}>{light ? <Moon size={16} strokeWidth={1.5} /> : <Sun size={16} strokeWidth={1.5} />}</button> }
export function LoadingLine() { return <span className="inline-flex items-center gap-2 text-13 text-text-secondary"><Loader2 size={14} className="animate-spin" />Loading</span> }

export function EmptyState({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <div className="rounded-card border border-dashed border-border-strong bg-surface-1 px-5 py-10 text-center"><h2 className="text-16 font-semibold">{title}</h2><p className="mx-auto mt-2 max-w-md text-13 text-text-secondary">{description}</p>{action && <div className="mt-5 flex justify-center">{action}</div>}</div> }
export function ErrorState({ message, retry }: { message: string; retry?: () => void }) { return <div role="alert" className="rounded-card border border-negative/40 bg-surface-1 p-5"><h2 className="text-14 font-semibold text-negative">Something went wrong</h2><p className="mt-2 text-13 text-text-secondary">{message}</p>{retry && <Button variant="secondary" className="mt-4" onClick={retry}>Try again</Button>}</div> }
export function ProgressBar({ value, label }: { value: number; label?: string }) { const n = Math.max(0, Math.min(100, value)); return <div><div className="flex justify-between font-mono text-[12px] text-text-secondary"><span>{label || 'Progress'}</span><span>{n}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-surface-3" role="progressbar" aria-label={label || 'Progress'} aria-valuemin={0} aria-valuemax={100} aria-valuenow={n}><div className="h-full bg-accent transition-[width]" style={{ width: `${n}%` }} /></div></div> }
export function FieldError({ children, id }: { children?: React.ReactNode; id?: string }) { if (!children) return null; return <p id={id} className="mt-1.5 text-[12px] text-negative">{children}</p> }
export function ConfirmDialog({ open, title, description, confirmLabel = 'Confirm', danger = false, onConfirm, onClose, busy = false }: { open: boolean; title: string; description: string; confirmLabel?: string; danger?: boolean; onConfirm: () => void; onClose: () => void; busy?: boolean }) { const dialog = useRef<HTMLDivElement>(null); const previous = useRef<Element | null>(null); useEffect(() => { if (!open) return; previous.current = document.activeElement; window.setTimeout(() => dialog.current?.querySelector<HTMLButtonElement>('button')?.focus(), 0); const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose(); if (e.key === 'Tab' && dialog.current) { const focusable = [...dialog.current.querySelectorAll<HTMLElement>('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])')]; if (!focusable.length) return; const first = focusable[0], last = focusable[focusable.length - 1]; if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus() } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus() } } }; document.addEventListener('keydown', onKey); return () => { document.removeEventListener('keydown', onKey); (previous.current as HTMLElement | null)?.focus?.() } }, [open, onClose]); return <AnimatePresence>{open && <motion.div className="fixed inset-0 z-[85] grid place-items-center bg-black/55 p-4 backdrop-blur-sm" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={onClose}><motion.div ref={dialog} role="alertdialog" aria-modal="true" aria-labelledby="confirm-title" aria-describedby="confirm-description" className="elevated w-full max-w-md p-5" initial={{ scale: .98, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} onMouseDown={e => e.stopPropagation()}><h2 id="confirm-title" className="text-18 font-semibold">{title}</h2><p id="confirm-description" className="mt-2 text-13 leading-5 text-text-secondary">{description}</p><div className="mt-6 flex justify-end gap-2"><Button variant="ghost" onClick={onClose} disabled={busy}>Cancel</Button><Button variant={danger ? 'danger' : 'primary'} onClick={onConfirm} disabled={busy}>{busy ? 'Working…' : confirmLabel}</Button></div></motion.div></motion.div>}</AnimatePresence> }
